# user.action - User-defined actions for Privoxy
# Add your custom actions here
#
# Example actions:
# {+block}
# .unwanted-site.com
#
# {+hide-user-agent{My Custom Agent}}
# .trusted-site.com
#
# This file is empty by default - add your own actions as needed 