version: '3.8'

services:
  nzbgetvpn:
    image: magicalyak/nzbgetvpn:latest
    container_name: nzbgetvpn
    ports:
      - "6789:6789" # NZBGet WebUI
      - "8118:8118" # Privoxy
      - "8080:8080" # Monitoring
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_MONITORING=yes
      # Add other nzbgetvpn environment variables here
      # - VPN_TYPE=openvpn
      # - VPN_CONFIG_FILE=your-vpn.ovpn
      # - VPN_USERNAME=your-user
      # - VPN_PASSWORD=your-pass
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - nzbgetvpn

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_DASHBOARDS_DEFAULT_FOLDER=nzbgetvpn

volumes:
  prometheus_data:
  grafana_data: 