name: 🐛 Bug Report
description: Report a bug or issue with nzbgetvpn
title: "[BUG] "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the README.md documentation
          required: true
        - label: I have checked the logs for error messages
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Set up container with...
        2. Configure VPN with...
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Configuration
      description: Your docker-compose.yml, docker run command, or relevant environment variables (please redact sensitive values)
      render: bash
      placeholder: |
        # Paste your docker-compose.yml, docker run command, or relevant environment variables here
        # Please be sure to redact any sensitive information like passwords or keys

  - type: textarea
    id: logs
    attributes:
      label: Container Logs
      description: Relevant log output from the container
      render: text
      placeholder: |
        Paste relevant log output here. You can get logs with:
        docker logs <container-name>
        or
        docker-compose logs nzbgetvpn

  - type: input
    id: version
    attributes:
      label: nzbgetvpn Version
      description: Which version/tag are you using?
      placeholder: "Example: v25.0.20 or latest"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or additional information here... 