name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the information below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue you're experiencing
      placeholder: "Example: Container fails to start with VPN error..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Container Logs
      description: Paste relevant log output (get with `docker logs <container-name>`)
      render: text
      placeholder: "Paste your container logs here..."

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your docker-compose.yml or docker run command (remove sensitive info)
      render: yaml
      placeholder: |
        # Paste your configuration here
        # Remove passwords, keys, and other sensitive information

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: "Example: latest, v25.0.20" 