name: 🚀 Feature Request
description: Suggest a new feature or enhancement for nzbgetvpn
title: "[FEATURE] "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the README.md documentation
          required: true
        - label: This feature would be beneficial to other users, not just my specific use case
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: "Describe the problem or limitation you're facing..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: "Describe your proposed solution in detail..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - VPN Configuration
        - NZBGet Configuration
        - Security & Privacy
        - Monitoring & Health Checks
        - User Interface / Web UI
        - Docker & Container Management
        - Networking
        - Logging & Debugging
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical/blocking issue
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Describe any alternative approaches you've thought about..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, examples, or references
      placeholder: |
        - Links to relevant documentation
        - Examples from other projects
        - Screenshots or mockups
        - Technical specifications
        - etc.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have ideas about how this could be implemented, share them here
      placeholder: "Any thoughts on potential implementation approaches..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be interested in implementing this feature myself
        - label: I would be willing to test this feature once implemented
        - label: I can provide additional feedback and requirements 