name: 🚀 Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: feature
    attributes:
      label: What would you like to see?
      description: Describe the feature or improvement you'd like
      placeholder: "Example: Add support for XYZ VPN provider..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      description: Explain how this would help users
      placeholder: "This would help because..."

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other details, examples, or context
      placeholder: "Links, examples, or other relevant information..." 