name: ❓ Question or Help
description: Ask a question about setup, configuration, or usage
title: "[QUESTION] "
labels: ["question", "help wanted"]

body:
  - type: markdown
    attributes:
      value: |
        Need help with nzbgetvpn? Please provide as much detail as possible so we can assist you effectively.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before asking your question
      options:
        - label: I have searched existing issues for similar questions
          required: true
        - label: I have read the README.md documentation thoroughly
          required: true
        - label: I have checked the container logs for error messages
          required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like help with?
      placeholder: "Ask your question here. Be as specific as possible..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: nzbgetvpn Version
      description: Which version/tag are you using?
      placeholder: "Example: v25.0.20 or latest"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs (if applicable)
      description: Any relevant log output
      render: text
      placeholder: |
        Paste relevant log snippets here. Get logs with:
        docker logs <container-name>
        or
        docker-compose logs nzbgetvpn

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide your configuration, what you've already tried, and any other relevant information.
      placeholder: "Paste your docker-compose.yml, docker run command, or any other configuration here. Please be sure to redact any sensitive information." 