name: ❓ Question
description: Ask a question or get help
title: "[QUESTION] "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Describe what you need help with
      placeholder: "Example: How do I configure XYZ VPN provider?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any relevant configuration, logs, or other details
      placeholder: |
        Include any relevant:
        - Configuration files (remove sensitive info)
        - Error messages or logs
        - What you've already tried 