name: Build and Publish Docker Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
    # Publish semver tags as releases.
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0, v1.2.3

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: magicalyak/nzbgetvpn # Explicitly set your Docker Hub image name

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to ghcr.io if used, good to have for Docker Hub too
      # id-token: write # Required for OIDC token if using keyless auth with cloud providers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up QEMU for multi-arch builds (optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Updated to v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5 # Updated to v5
        with:
          images: ${{ env.IMAGE_NAME }} # Use the explicitly defined IMAGE_NAME
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=branch,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha,prefix=,suffix=,event=branch,enable={{is_default_branch}}
            type=sha,prefix=,suffix=,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5 # Updated to v5
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }} # Do not push on PRs
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
