name: Test Docker Hub Push

on:
  workflow_dispatch:

env:
  REGISTRY_DOCKERHUB: docker.io
  IMAGE_NAME: magicalyak/nzbgetvpn

jobs:
  test-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate Docker Hub credentials
        run: |
          if [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]]; then
            echo "❌ DOCKERHUB_USERNAME secret is not set"
            exit 1
          elif [[ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]]; then
            echo "❌ DOCKERHUB_TOKEN secret is not set"
            exit 1
          else
            echo "✅ Docker Hub credentials are configured"
            echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
            echo "Username length: ${#DOCKERHUB_USERNAME}"
            echo "Token length: ${#DOCKERHUB_TOKEN}"
          fi
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_DOCKERHUB }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test push with simple image
        run: |
          # Create a simple test image
          echo "FROM alpine:latest" > Dockerfile.test
          echo "RUN echo 'Test image for Docker Hub authentication'" >> Dockerfile.test
          
          # Build and push test image
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile.test \
            --tag ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}:test \
            --push \
            .
          
          echo "✅ Test push successful!"

      - name: Clean up test image
        run: |
          # Note: This won't delete from Docker Hub, just locally
          docker rmi ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}:test || true 